### ISSUE TITLE
--dry-run option requires the --verbose flag to actually display all commands.

### ISSUE THREAD

**Issue by slavistan** [codecircuit/minstructor#14]
**Using the `minstructor --dry-run` only prints the random excerpt, whereas appending the verbosity flag does do the job. This seems unintentional.**

Executing `minstructor "runme.sh range(1, 20)" --dry-run -f` yields 

```sh
Here is an random excerpt of your in total 19 generated commands:
runme.sh 14
runme.sh 11
runme.sh 4
runme.sh 5
runme.sh 18
runme.sh 1
runme.sh 2
runme.sh 17
runme.sh 15
runme.sh 12
runme.sh 9
runme.sh 16
runme.sh 3
runme.sh 7
runme.sh 6
Progress: |================================================================================================================================================================================================|
Nothing has been executed; this has been a dry run
```
whereas `minstructor "runme.sh range(1, 20)" --dry-run -f --verbose` does print all 20 commands as requested.

```sh
The Measurement Instructor generated the following commands for you:
runme.sh 1
runme.sh 2
runme.sh 3
runme.sh 4
runme.sh 5
runme.sh 6
runme.sh 7
runme.sh 8
runme.sh 9
runme.sh 10
runme.sh 11
runme.sh 12
runme.sh 13
runme.sh 14
runme.sh 15
runme.sh 16
runme.sh 17
runme.sh 18
runme.sh 19
Executing: 'runme.sh 1'
Executing: 'runme.sh 2'
Executing: 'runme.sh 3'
Executing: 'runme.sh 4'
Executing: 'runme.sh 5'
Executing: 'runme.sh 6'
Executing: 'runme.sh 7'
Executing: 'runme.sh 8'
Executing: 'runme.sh 9'
Executing: 'runme.sh 10'
Executing: 'runme.sh 11'
Executing: 'runme.sh 12'
Executing: 'runme.sh 13'
Executing: 'runme.sh 14'
Executing: 'runme.sh 15'
Executing: 'runme.sh 16'
Executing: 'runme.sh 17'
Executing: 'runme.sh 18'
Executing: 'runme.sh 19'
Nothing has been executed; this has been a dry run
```

Also, it would be nice if the dry-run output consisted of the actual commands only (`runme.sh 16` only without the corresponding `Executing: 'runme.sh 16'`) so it may be directly used without the need to remove the parts which are not shell-executable.

Cheers!

**Comment by codecircuit** [comment]
We can discuss if it is reasonable if `--dry-run` also enable verbose behaviour. In particular `--dry-run` only disable the actual command execution, but nothing else right now. 

To adress your problem `minstructor` should show the output of the program executions in your terminal, if no output directory is specified. Since this is not working at the moment, this is a bug.
