### ISSUE TITLE
In linspace() and logspace(), emit integral values without decimal point

### ISSUE THREAD

**Issue by mbeutel** [codecircuit/minstructor#17]
When using `linspace()` and `logspace()`, `minstructor` reasonably uses floating-point math to compute the desired values. However, these functions are often used to generate sequences of integers. But `minstructor` prints even integral numbers with a decimal point. Example:

```
$ minstructor -o (...)/foo/ "echo linspace(0,2,3)"
The Measurement Instructor generated the following commands for you:
echo 0 > (...)/foo/out_0.txt
echo 1.0 > (...)/foo/out_1.txt
echo 2.0 > (...)/foo/out_2.txt
```

This can be a problem if the command expects an integral argument and fails with a parse error if it finds a decimal point. Hence it would be desirable to suppress the decimal point for all values which happen to be integer:

```
$ minstructor -o (...)/foo/ "echo linspace(0,2,3)"
The Measurement Instructor generated the following commands for you:
echo 0 > (...)/foo/out_0.txt
echo 1 > (...)/foo/out_1.txt
echo 2 > (...)/foo/out_2.txt
```

A possible implementation can be found in the following commit in my fork:
https://github.com/mbeutel/minstructor/commit/0097a095d445272f9115d80e6ae551b1624a7dcd

I can make it a pull request if desired.

**Comment by mbeutel** [comment]
Another possible approach would be to add a new command-line argument `--round` which would round all values produced by `linspace()` and `logspace()` to the nearest integer. This would be very useful in itself, e.g. to produce finer-grained log-spaced sequences such as `[1, 2, 5, 10, 20, 50, ...]`. Perhaps I'll write another feature request for this...

**Comment by codecircuit** [comment]
I disagree with an additional flag. This should be represented by the function itself, e.g. `rlogspace` for rounded values on log space, or `logrange`. This is not implemented yet. If it is desired another issue should be opened for that.

But I implemented your first point, based on your fork. Generally I would rather prefer to have floating point numbers for `???space` functions, but I see the usefulness to emit integral values for the `logspace` function. To generate integer values on a linear space, one should use the `range` and not the `linspace` function.
