### ISSUE TITLE
Handle single-valued lists consistently

### ISSUE THREAD

**Issue by mbeutel** [codecircuit/minstructor#18]
`minstructor` currently doesn't treat empty or single-valued lists as lists:

```
$ minstructor -o (...)/foo/ "echo [1]"
The Measurement Instructor generated the following commands for you:
echo [1] > (...)/foo/out_0.txt

$ minstructor -o (...)/foo/ "echo []"
The Measurement Instructor generated the following commands for you:
echo [] > (...)/foo/out_0.txt
```

It would be very useful for scripting scenarios and more consistent overall if `minstructor` handled single-valued and empty lists as lists:

```
$ minstructor -o (...)/foo/ "echo [1]"
The Measurement Instructor generated the following commands for you:
echo 1 > /home/nfs/kmbeutel/foo/out_0.txt

$ minstructor -o (...)/foo/ "echo []"
Error: zero commands in list
```

(I would also find it useful to not consider it an error if there is a factor of 0 in the Cartesian product of argument sets, but that would be a separate request; here I'm being consistent with `linspace()` and `logspace()` which both raise errors if the generated list of arguments is empty.)

**Comment by codecircuit** [comment]
This would disable the current possibility to use a linked list logic with `minstructor`. See discussion in #23.

**Comment by codecircuit** [comment]
Fixed on develop.
