### ISSUE TITLE
mcollector should not take a list of files as command-line argument

### ISSUE THREAD

**Issue by mbeutel** [codecircuit/minstructor#19]
`mcollector` is typically called with a glob that expands to a list of output files:
```
mcollector /foo/bar/baz/*
```

This approach is problematic because the Linux kernel imposes a hard limit on the command-line argument size:

https://www.in-ulm.de/~mascheck/various/argmax/

This limit is typically in the megabyte range:

```
$ getconf ARG_MAX
2097152
```

If the number of output files is large and/or the output path is deeply nested, one can run into errors like `command: arg list too long` when using `mcollector`.

Hence, instead of passing a list of files to `mcollector`, it might be helpful to pass a list of directories and have `mcollector` recursively enumerate the files in these directories itself.

To avoid a breaking change, perhaps we could have an additional flag argument `-d|--directories` which tells `mcollector` that the arguments passed in are supposed to be directories:

```
mcollector -d /foo/bar/baz
```

**Comment by codecircuit** [comment]
Now `mcollector` can also process directories (also recursive with `-r`)
